export type ReportType =
  | 'CLAIMS_OUTSTANDING'
  | 'PAYEE'
  | 'REVENUE_ANALYSIS'
  | 'MOVEMENT_SUMMARY'
  | 'CLAIMS_REGISTER';

export interface ImportTypeConfig {
  key: string;
  fileTypeKey: ReportType;
  title: string;
  description: string;
  frequency: 'Daily' | 'Weekly' | 'Monthly' | 'On demand';
  templateHref: string;
  endpoint: string;
  requiredColumns: string[];
  allColumns: string[];
  notes: string;
  parserWarnings?: string[];
  successMessage: string;
}

export const IMPORT_TYPES: ImportTypeConfig[] = [
  {
    key: 'claims',
    fileTypeKey: 'CLAIMS_OUTSTANDING',
    title: 'Detailed Claims Paid & Outstanding',
    description:
      'Daily SpreadsheetML XLS report containing all active claims, financial positions, and reserve details.',
    frequency: 'Daily',
    templateHref: '/templates/claims_outstanding_template.csv',
    endpoint: '/api/import/claims',
    requiredColumns: [
      'Claim',
      'Claim Handler',
      'Claim Status',
      'Secondary Claim Status',
      'DOL',
      'Cause',
      'Intimated Amount',
      'Total Paid',
      'Total Outstanding',
      'Total Incurred',
    ],
    allColumns: [
      'Claim',
      'Old Claim Number',
      'Claim Handler',
      'Claim Status',
      'Secondary Claim Status',
      'Organisational Unit',
      'Underwriting Year',
      'Group Description',
      'Section Description',
      'Policy',
      'Insured',
      'Broker',
      'DOL',
      'Cause',
      'Intimated Amount',
      'Own Damage Paid',
      'Third Party Paid',
      'Legal Costs Paid',
      "Assessor's Fees Paid",
      'Repair Authorisation Paid',
      'Cash In Lieu of Repairs Paid',
      'Glass Authorisation Paid',
      'Parts Authorisation Paid',
      'Towing, Storage, Release Fees Paid',
      'Additionals Paid',
      'Third Party Liability Paid',
      'Investigation Paid',
      'Expenses Paid',
      'Total Paid',
      'Total Recovery',
      'Total Salvage',
      'Own Damage Outstanding',
      'Third Party Outstanding',
      'Legal Costs Outstanding',
      "Assessor's Fees Outstanding",
      'Repair Authorisation Outstanding',
      'Cash In Lieu of Repairs Outstanding',
      'Glass Authorisation Outstanding',
      'Third Party Liability Outstanding',
      'Expenses Outstanding',
      'Total Outstanding',
      'Total Incurred',
      'Section Sum Insured',
      '100% Deductible',
      'Retained %',
      'Area of Target (Capacity Purposes)',
      'Loss Address',
    ],
    notes:
      'Standard xlsx format. Row 0 is the header row. Snapshot date is set to today (the upload date).',
    parserWarnings: [
      'Row 1 may contain a sequence number artefact — skipped automatically by the parser.',
      'Snapshot date is the upload date, not a date embedded in the file.',
    ],
    successMessage:
      'Daily delta has been computed. TAT flags, claim velocity, and fraud signals have been updated.',
  },
  {
    key: 'payee',
    fileTypeKey: 'PAYEE',
    title: 'Payee Report',
    description:
      'Payments register with cheque details, payees, authorisation dates, and gross amounts.',
    frequency: 'Daily',
    templateHref: '/templates/payee_template.csv',
    endpoint: '/api/import/payee',
    requiredColumns: [
      'Claim Number',
      'Claims Handler',
      'Payee',
      'Cheque Requested',
      'Cheque Authorised',
      'Cheque Printed',
      'Gross Paid Incl VAT',
      'Estimate Type',
    ],
    allColumns: [
      'Team Name',
      'Group',
      'Group Name',
      'Product',
      'Section',
      'M/N',
      'Broker',
      'Claims Handler',
      'Claim Number',
      'Old Claim No',
      'Secondary Status',
      'Claim Status',
      'Policy Number',
      'Insured',
      'Date Of Loss',
      'Date Of Notification',
      'Date Of Registration',
      'Cheque No',
      'Payee',
      'Payee VAT Nr',
      'Cheque Requested',
      'Cheque Authorised',
      'Cheque Printed',
      'Payment(s) Requested By',
      'Estimate Type',
      'Gross Paid Incl VAT',
      'Gross Paid Excl VAT',
      'Quota Share Excl VAT',
      'Open Market Fac Excl VAT',
      'XOL Excl VAT',
      'Surplus Excl VAT',
      'Net Paid Incl VAT',
      'Underwriting Date',
    ],
    notes:
      'Standard single-header-row XLS. System computes same-day auth/print flag, self-authorised flag, and days from request to print.',
    parserWarnings: [
      'Cheque dates may be empty for pending payments — imported as null.',
      'Payee VAT Nr may be blank for individuals — this is expected.',
    ],
    successMessage:
      'Payment integrity flags have been computed. Self-authorisation and same-day print checks are updated.',
  },
  {
    key: 'revenue',
    fileTypeKey: 'REVENUE_ANALYSIS',
    title: 'Revenue Analysis Detailed Report',
    description:
      'Monthly premium and commission data by broker, class, and underwriting year for loss ratio calculations.',
    frequency: 'Weekly',
    templateHref: '/templates/revenue_analysis_template.csv',
    endpoint: '/api/import/revenue',
    requiredColumns: [
      'Month',
      'Class Name',
      'Broker',
      'Net WP',
      'GWP',
      'Endorsement Type',
      'Underwriting Year',
    ],
    allColumns: [
      'Month',
      'Branch',
      'Branch Name',
      'Class',
      'Class Name',
      'Frequency',
      'Product',
      'Broker',
      'Policy',
      'Insured',
      'Effective Date',
      'Expiry Date',
      'Inception Date',
      'Renewal Date',
      'Underwriting Year',
      'GWP',
      'Quota Share WP',
      'RIWP',
      'Net WP',
      'Gross Comm',
      'Quota Share Comm',
      'RI Comm',
      'Net Comm',
      'Gross Comm %',
      'Quota Share Comm %',
      'U/W Fee',
      'GWP VAT',
      'Quota Share WP VAT',
      'Gross Comm VAT',
      'Quota Share Comm VAT',
      'Premium Collection Option',
      'Country',
      'L/F',
      'AMS Type',
      'Renewal Frequency',
      'Marketer',
      'Endorsement Type',
      'Overrider',
      'Overrider %',
      'Currency',
      'System',
    ],
    notes:
      'Loss ratio uses Net WP where Endorsement Type is Renewal or New Business only. Cancellations and Endorsements are excluded from the denominator.',
    parserWarnings: [
      'Only Renewal and New Business rows are used for loss ratio calculation.',
      'Negative amounts appear as (1,423.30) for cancellations — parsed correctly.',
    ],
    successMessage:
      'Loss ratio and broker premium data have been updated. Financial dashboard will reflect new figures.',
  },
  {
    key: 'movement',
    fileTypeKey: 'MOVEMENT_SUMMARY',
    title: 'Month-End Summary Movement Report',
    description:
      'Monthly financial movement report with UPR, IBNR, SASRIA, and underwriting result by section.',
    frequency: 'Monthly',
    templateHref: '/templates/movement_summary_template.csv',
    endpoint: '/api/import/movement',
    requiredColumns: ['Level', 'Paid', 'OS Open', 'OS Close', 'OS Movement', 'Incurred'],
    allColumns: [
      'Period',
      'Section',
      'Level',
      'Paid',
      'OS Open',
      'OS Close',
      'OS Movement',
      'Incurred',
      'Premium',
      'Commission',
      'Net Premium',
      'Loss Ratio',
      'UPR Open',
      'UPR Close',
      'UPR Movement',
      'DAC Open',
      'DAC Close',
      'DAC Movement',
      'SASRIA Premium',
      'SASRIA Claims',
      'SASRIA Net',
      'U/W Result',
      'Combined Ratio',
      'Expense Ratio',
    ],
    notes:
      'Non-standard file structure — summary with section headers, not a flat table. Parser reads named sections: Claims, UPR, DAC, SASRIA, U/W Result.',
    parserWarnings: [
      'This file has a non-standard structure with section headers — not a flat table.',
      'Do not use a regular spreadsheet parser. The system uses a custom section-aware parser.',
      'Preview is not available for this report type due to its summary structure.',
    ],
    successMessage:
      'U/W result, IBNR movement, and SASRIA figures have been updated in the financial dashboard.',
  },
  {
    key: 'claims-register',
    fileTypeKey: 'CLAIMS_REGISTER',
    title: 'Claims by Initial Registration Date',
    description:
      'Provides dateOfRegistration for every claim regardless of payment status. Fixes zero-payment claim age gaps.',
    frequency: 'Daily',
    templateHref: '/templates/claims_register_template.csv',
    endpoint: '/api/import/claims-register',
    requiredColumns: [
      'Claim',
      'Date Captured',
      'Captured By',
      'Claim Handler',
      'Claim Status',
      'Date of Loss',
    ],
    allColumns: [
      'Claim',
      'Old Claim ID',
      'Claim Handler',
      'Captured By',
      'Date Captured',
      'Date of Loss',
      'Claim Status',
      'Secondary Status',
      'Claim Cause',
      'Intimated Amount',
      'Insured',
      'Broker',
      'Policy',
      'Class',
      'Class Name',
      'ProductGroup',
      'Organisational Unit',
      'Gross Incurred',
      'Catastrophe',
    ],
    notes:
      'Header row is at row 3 (rows 1–2 are title/subtitle). Snapshot date is the upload date.',
    parserWarnings: [
      'Rows 1 and 2 are skipped — the parser treats row 3 as headers.',
      'Claims with no Date Captured are skipped.',
    ],
    successMessage:
      'Registration dates and catastrophe flags have been applied. Claim age calculations are updated.',
  },
];
